### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by AnotherKamila** [bergercookie/taskw_gcal_sync#1]
Hello,

I've been hoping for a gcal/taskwarrior sync tool for a long time. What is the current status of this? And could you please add installation and usage instructions into the README?

BTW, I would be interested in helping with the development if this fits my need, although right now I am rather overwhelmed, so I can't promise anything.

Thanks a lot!

**Comment by bergercookie** [comment]
Hello @AnotherKamila,

This is merely a work in progress,

I was hoping of having it implemented by now but I had too much on my plate. I might crack on it the following weeks if I've got the time though.

Stay tuned,
Nikos

**Comment by boydkelly** [comment]
On Fedora 27 I had to:
1018  pip install rfc3339
 1020  pip install bidict
 1024  pip install pypref
I now get this....  (Sorry I'm not a programmer othewise I would love to help.  Very interested in this.)
python tw_gcal_sync.py 
Traceback (most recent call last):
  File "tw_gcal_sync.py", line 3, in <module>
    from taskw_gcal_sync import TWGCalAggregator, GCalSide, TaskWarriorSide
  File "/usr/local/src/taskw_gcal_sync/taskw_gcal_sync/__init__.py", line 4, in <module>
    from taskw_gcal_sync.aggregator import TWGCalAggregator
  File "/usr/local/src/taskw_gcal_sync/taskw_gcal_sync/aggregator.py", line 15, in <module>
    class Preferences(PREF):
  File "/usr/local/src/taskw_gcal_sync/taskw_gcal_sync/aggregator.py", line 29, in Preferences
    ad_lines=self.ad_lines):
NameError: name 'self' is not defined

**Comment by bergercookie** [comment]
Hey @AnotherKamila, @boydkelly,

I'm in progress of refactoring and (at last) publishing an actual working version of this
Stay tuned.

**Comment by bergercookie** [comment]
Hey @AnotherKamila , @boydkelly,


There's a working version of taskw_gcal_sync live, tag:v0.3. It supports creation, modification, deletion of events from either GCal, or TW.

Let me know if this useful or if there's something that doesn't work etc.
