### ISSUE TITLE
Is only google calendar supported?

### ISSUE THREAD

**Issue by ngortheone** [bergercookie/taskw_gcal_sync#10]
I have my own [Zimbra](https://www.zimbra.com/) server, which has CalDav if I am not mistaken.
Is it possible to sync with it?

**Comment by bergercookie** [comment]
No, it's not.
Current  implementation only works with gcal.

However, it shouldn't be too hard extending it for CalDev. One would need to create a `CalDevSide` class that inherits from `GenericSide` as well as a `TWCalDevAggregator` for communicating between TW and CalDev.
