### ISSUE TITLE
Google to review `taskw_gcal_sync`

### ISSUE THREAD

**Issue by bergercookie** [bergercookie/taskw_gcal_sync#15]
Currently taskw_gcal_sycn appears as an unsafe, and unreviewed app when connecting it to one's Google account.

**Comment by bergercookie** [comment]
Don't really know what's the process, should do some research

**Comment by Scefing** [comment]
Looks to be the Google OAuth API Verification thing: [https://support.google.com/cloud/answer/9110914?hl=en](FAQ here). If you don't get verified it seems like there's a 100-user quota cap now, so you might want to get verified in case this gets popular.

**Comment by bergercookie** [comment]
Will be handled as part of https://github.com/bergercookie/taskw_gcal_sync/issues/24

**Comment by bergercookie** [comment]
> EDIT: You're really not supposed to have the client secret publicly available, take a look at this article on OAuth authorization codes and consider how you want to implement OAuth here.

Hi @eacpereira , took me a while to answer here :) 

I think that's not the case when it comes to desktop apps.
Basically there are two ways for users to use this app. Either I embed this client secret in the repo as I'm currently doing, OR I have each one of them create a developer account at Google, create a test app and paste the credentials for my app to use them instead.

I think that for desktop apps, the client secret inevitably is not a secret any more.. it just comes down to wrong naming by Google. This answer on SO gives a bit more insight: https://stackoverflow.com/a/20571986/2843583
