### ISSUE TITLE
Several errors in the logs

### ISSUE THREAD

**Issue by Petemir** [bergercookie/taskw_gcal_sync#28]
Hello,

I am sorry for not being able to be more clear in the title nor the following description, but I am having diverse errors when trying to synchronize. I originally created the tasks in taskwarrior and did the sync, expecting to see the tasks in Gcal. That occurred, but I guess something wrong happened with subsequent syncs, and now I have some calendar events which only say "day" -which actually seems to be the 'description' of the tasks, and not the title?-, and the same happens on my task list. 

I attach in a file the errors I got. I redacted some tasks titles ($Task1, $Task2) and annotations ($Annotation1, $Annotation2). I left the 'day' title though.

[twgcalsync_errors.log](https://github.com/bergercookie/taskw_gcal_sync/files/6802254/twgcalsync_errors.log)

Let me know if there's anything I can do to help debug the issue, and thanks in advance.

Edit:

So, any of the problems here messed up my task list... e.g. $Task1 appears as deleted in taskwarrior now, although I never deleted it, not in Calendar nor TW.

**Comment by Petemir** [comment]
Sorry, it seems that I f*cked up with the "day" thing :), but I am not sure about the deleted task, nor the recurrent errors in syncing.

**Comment by bergercookie** [comment]
Hi @Petemir ,

Closing this, see #30
