### ISSUE TITLE
Still can't authorize access to my calendar

### ISSUE THREAD

**Issue by kcallis** [bergercookie/taskw_gcal_sync#29]
I have followed all of the instruction, but when I attempt to sync my calendar with TW, I get the following message:

```
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=2962XXXXXXXX-jja1pq86bu30jgdocfchn8j5XXXXXXXX.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar&state=SfLgzC3JOVZYhL0BWGGWsgXXXXXXXX&access_type=offline
```

I am not overly knowledgeable about google products and tools, so I am at a loss.

**Comment by bergercookie** [comment]
Hi @kcallis ,

For now you have to set up a new dev account on google for this to work as I haven't yet authorized the app.
Please follow these instructions and let me know if it doesn't work. https://github.com/bergercookie/taskw_gcal_sync#override-calendar-api-key
