### ISSUE TITLE
v1.0 Release - more robust workflow

### ISSUE THREAD

**Issue by bergercookie** [bergercookie/taskw_gcal_sync#30]
Hi all,

Thanks for using this project.
I've now released version 1.0 which should be less error/exception-prone to the last version.

More specifically the overall workflow for how to update/insert/delete items from one side to the other is now an independent package, in[item-synchronizer](https://github.com/bergercookie/item-synchronizer). This is overall better written and better unittested and should hopefully improve the overall usability of this application as well.

I'll be closing any issues that have to do with syncrhonisation problems since they may now be dealt with via the application re-design.
Feel free to re-open if they don't work as expected.

**Comment by YakBarber** [comment]
The URL doesn't work. I think you mean https://github.com/bergercookie/item_synchronizer.

Thank you for your work on these tools by the way.

**Comment by bergercookie** [comment]
I corrected it, thanks for the kind words :)
