### ISSUE TITLE
Handling tasks in order of urgency instead of ID

### ISSUE THREAD

**Issue by StefanBRas** [bergercookie/taskw_gcal_sync#8]
Hi.

Is it/could one make it possible to specify which order to create/delete/handle the tasks in? In my case, I would like to handle them by urgency. I believe that right now, they're handled according to ID.

If you give my some pointers to where things would have to be changed in the code, I can perhaps change it myself.

It probably sounds like an odd request, so i'll have to explain my setup and why it matters.

I use taskw_gcal_sync to sync taskwarrior tasks I want to view from my (Android) phone. But I don't view them directly through google calendar - instead i use the todo-app TickTick which can import tasks from google calendar. I do so, because it lets me see my most urgent tasks on my lock screen and in my notification bar - and I can mark them as done. Also I can easily see all the individual tasks, which is difficult in google calendar when I have many small tasks scheduled.  So as an example, when I have to do various kinds of housework i create a task for each thing and then sync all those tasks. 

Apparently if two tasks have the same due time, they are listed in the order they are created. So to achieve the right order, I have to schedule them all one minute apart in the order I want.

Hopefully it makes sense.

Kind regards
Stefan

**Comment by bergercookie** [comment]
OK, so I suppose you don't want the ordering based on the urgency to be both ways right, i.e., you need to specify the order only when they are copied from TW to Google Calendar?

**Comment by bergercookie** [comment]
I'm not sure I understand your question.
What do you mean "handle tasks in order of urgency"?

What I understand from this is "push the taskwarrior tasks to google calendar in descending order (from the most urgent to the least urgent)", is this accurate? What good would that do though? Does the app you are using detects the Google Calendar creation dates and sorts them using the latter?

**Comment by bergercookie** [comment]
If you are looking for the latter take a look at the latest `devel` branch. You can run taskw_gcal_sync as below to achieve what you want:

```
 ./tw_gcal_sync -c "TW Reminders" -t "remindme" --order-by=urgency --descending-order
```

Make sure you also get the latest version of my fork of `taskw` as I had to fix a bug in the latter as well.

**Comment by bergercookie** [comment]
OK, closing this, let me know if this doesn't work for you.
